#!/usr/bin/bash
  input_file="$1"
    while IFS= read -r number || [[ -n "$number" ]]; 
    do
        factors=$(factorize "$number")
        for factor in $factors; 
            echo "$number=$factor*$(($number / $factor))"
    done < "$input_file"
