#!/usr/bin/bash
  input_file="$1"
    while IFS= read -r numbers || [[ -n "$numbers" ]]; 
    do
        factors=$(factorize "$numbers")
        for factor in $factors; 
		echo "$numbers = $(($numbers / $(factors[1]) *$(($factors[1]))"
    done < "$input_file"
